### PR TITLE
Replace the onKeyDown & onKeyUp events

### PR DESCRIPTION
**Pull request by dad72**
Replace the onKeyDown and onKeyUp events with a single BABYLON observable that I name _onKeyBoardObservable.
So it will always be compatible with future versions of browsers.

### CODE REVIEW

**Comment by dad72** [comment]
It has been tested and it works. Besides, I also tested with a glTF character and it works much better in terms of collisions with the ground.

However, I noticed a problem here:

```
let myWalkAnimationGroup:AnimationGroup = ...;
let agMap = {
     "walk":myWalkAnimationGroup,
     "run" : {"ag": myRunAnimationGroup,"rate": 1},
     "idle" : {"ag": myIdleAnimationGroup,"loop": true,"rate": 1},     
};
```
`"walk": myWalkAnimationGroup,`  **This works**
**But this not works :**
```
"run" : {"ag":myRunAnimationGroup,"rate":1},
"idle" : {"ag":myIdleAnimationGroup,"loop":true,"rate":1},
```

Maybe I used it wrong. while doing it like this, it work :
`setIdleAnim(animationGroups.idle, 1.0, true);`

Maybe I should open a new issue for this?

**Comment by ssatguru** [comment]
Sorry for the delay in looking into this but I am not sure why we should complicate things with observable. Why add another library dependency?. The current code is simple, will not become deprecated anytime soon and do not require any additional library

**Comment by dad72** [comment]
There are no additional libraries.

Observables are built into Babylon and its more modern use of events.

**Comment by ssatguru** [comment]
Yes it is in Babylon but is still additional library. It is not part of
standard JavaScript. Browser don't support it natively

**Comment by dad72** [comment]
The CharacterControler refers to Babylon. It can only work with Babylon. Your whole class is not just from Javascript, but from Babylon. So no additional library anyway because your class will not work without the Babylon library.

You are using BABYLON.Vector3... There is nothing more different or additional than using a BABYLON.Observable.
Observables are the future, more modern than of simples calls onKeyDown onKeyUp and all the code around it.

But you do as you wish. But I think it's a good improvement to use observables in the future. Javascript is starting to integrate them too, because they are more efficient.

**Comment by ssatguru** [comment]
I looked into this more.
Babylonjs does not use any library to provide observable.
They have implemented this pattern themselves.
You can see this here
https://github.com/BabylonJS/Babylon.js/blob/master/packages/dev/core/src/Misc/observable.ts#L99
Though I am not very keen on adding this, I will research this further to see if it provides any additional value.

**Pull request closed without merging**
